services:
  - type: web
    name: rabbitmq-service
    env: docker
    dockerfilePath: ./Dockerfile
    plan: standard
    disk:
      name: rabbitmq-data
      mountPath: /var/lib/rabbitmq
      sizeGB: 1
    envVars:
      - key: RABBITMQ_DEFAULT_USER
        value: usuario
      - key: RABBITMQ_DEFAULT_PASS
        generateValue: true
    ports:
      - port: 15672
        name: management
        external: true  # Hacer externo explícitamente
      - port: 5672
        name: amqp
        external: true  # Hacer externo explícitamente
    healthCheckPath: /
    healthCheckTimeout: 120
